# Generated by Django 4.2.5 on 2023-09-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='todo')),
                ('description', models.TextField(verbose_name='description')),
                ('date_created', models.DateTimeField(verbose_name='date and time created')),
            ],
        ),
    ]
