# Generated by Django 4.2.5 on 2023-09-05 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Список дел'},
        ),
        migrations.AddField(
            model_name='todo',
            name='date_to_complete',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date to be completed'),
            preserve_default=False,
        ),
    ]
