# Generated by Django 4.2.5 on 2023-09-05 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todo_options_todo_date_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 19, 13, 17, 205521), verbose_name='date and time created'),
        ),
    ]
