# Generated by Django 4.2.5 on 2023-09-05 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_todo_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=0, verbose_name='is task done'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 20, 59, 2, 297718), verbose_name='date and time created'),
        ),
    ]
